### ISSUE TITLE
Investigate data-issue with invalid masks

### ISSUE THREAD

**Issue by apacha** [OMR-Research/muscima-pp#6] opened 2020-12-01 10:20 UTC
Some masks seem to be causing problems after upgrading to version 2.0, as reported by @j0ner0n in this ticket: https://github.com/OMR-Research/MungLinker/issues/4

Investigate the source of this problem.

**Comment by jonas4climate** [comment] 2021-02-09 07:27
The mask issues were not caused by the v2 upgrade but in fact were simply caused by the wrong annotation and image files being paired up during data loading in the MuNGlinker. This has been addressed and resolved in the PR [here](https://github.com/OMR-Research/MungLinker/pull/5).

**Closed as completed** 2021-02-09 07:28 UTC
Labels: bug
